# Estágio 1: Compilação (Build)
FROM maven:3.8.5-openjdk-17 AS build
COPY . .
RUN mvn clean install -DskipTests -Pproduction

# Estágio 2: Execução (Runtime)
# Trocamos a imagem obsoleta por uma ativa e segura
FROM eclipse-temurin:17-jdk-alpine
COPY --from=build /target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]