# Estágio 1: Compilação (Build)
FROM maven:3.8.5-openjdk-17 AS build
COPY . .
RUN mvn clean install -Pproduction

# Estágio 2: Execução (Runtime)
FROM openjdk:17-jdk-slim
COPY --from=build /target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]